# Generated by Django 3.0.6 on 2020-06-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='doctor status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_patient',
            field=models.BooleanField(default=False, verbose_name='patient status'),
        ),
    ]
